[2018-12-13 21:49:40] request.INFO: Matched route "admin_module_manage". {"route":"admin_module_manage","route_parameters":{"category":null,"keyword":null,"_controller":"PrestaShopBundle\\Controller\\Admin\\ModuleController::manageAction","_legacy_controller":"AdminModulesManage","_route":"admin_module_manage"},"request_uri":"http://localhost/presta/admin7270ibkv6/index.php/module/manage?_token=dU3huZyCW96wyVhFsCElbKsZfrrQFvxt_wKQH61fQ6g","method":"GET"} []
[2018-12-13 21:49:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"} []
[2018-12-13 21:49:40] security.DEBUG: User was reloaded from a user provider. {"provider":"PrestaShopBundle\\Security\\Admin\\EmployeeProvider","username":"adekse@gmail.com"} []
[2018-12-13 21:49:45] app.ERROR: Data from PrestaShop Addons is invalid, and cannot fallback on cache.  {"exception":"cURL error 28: Operation timed out after 5000 milliseconds with 975129374883840 bytes received"} []
[2018-12-13 21:49:47] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2018-12-21 10:56:12] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Error: Maximum execution time of 30 seconds exceeded" at C:\xampp2\htdocs\presta\classes\Tools.php line 1982 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Maximum execution time of 30 seconds exceeded at C:\\xampp2\\htdocs\\presta\\classes\\Tools.php:1982)"} []
